---
- hosts: routers
  become: yes

  tasks:
    - name: Create Loopback999
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback888
            description: Configured in Ansible-startup Lab
            enabled: true

    - name: Configure ip helpers on multiple interfaces
      cisco.ios.ios_config:
        lines:
          - ip helper-address 172.26.1.10
          - ip helper-address 172.26.3.8
        parents: "{{ item }}"
      with_items:
        - interface Loopback888
        - interface Loopback999
        - interface FastEthernet3/1

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified




