aps:
- ap: AP_DAVINCI_HUB_MEDIA
bridge_domains:
- bd: BD_Default
  gateway: 192.168.0.1
  mask: '24'
  scope: public
contracts:
- contract: CON_EPG_L3OUT-to-EPG_DAVINCI_HUB_MEDIA
  filter: TCP_2101_FLT
  scope: vrf
  subject: SUBJ_EPG_L3OUT-to-EPG_DAVINCI_HUB_MEDIA
epg_contracts:
- ap: AP_DAVINCI_HUB_MEDIA
  contract: CON_EPG_L3OUT-to-EPG_DAVINCI_HUB_MEDIA
  contract_type: provider
  epg: EPG_DAVINCI_HUB_MEDIA
  scope: vrf
epgs:
- ap: AP_DAVINCI_HUB_MEDIA
  bd: BD_Default
  encap: '22'
  epg: EPG_DAVINCI_HUB_MEDIA
external_epg:
- contract: CON_EPG_L3OUT-to-EPG_DAVINCI_HUB_MEDIA
  contract_type: consumer
  l3out_ext_epg: EXT_EPG_Default
  l3out_name: L3OUT_Default
filters:
- entry: TCP_2101_FLT
  filter: TCP_2101_FLT
  port_from: '2101'
  port_to: '2101'
  protocol: tcp
tenant: TN_Default
vrf: VRF_Default
